route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 3h
  receiver: 'discord'

# receivers:
#   - name: 'email-notifications'
#     email_configs:
#       - to: 'your-email@example.com'
#         from: 'alertmanager@example.com'
#         smarthost: 'sandbox.smtp.mailtrap.io:587'
#         auth_username: '747a4f6a283fe8'
#         auth_password: '40158186ac93cf'


receivers:
- name: discord
  discord_configs:
  - webhook_url: 'https://discord.com/api/webhooks/1239567302333042739/OMbD9F_0n8PE1EwbOZxXRKiUuIjxYNdhKv32hOx_9Jfyyztl5NEyfdBgvqZFeBuaQHKx'