global:
  scrape_interval: 15s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'web-app'
    static_configs:
      - targets: ['app-web912617.westeurope.cloudapp.azure.com:8082']

  - job_name: 'database'
    static_configs:
      - targets: ['app-database347477.westeurope.cloudapp.azure.com:9104']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['app-web912617.westeurope.cloudapp.azure.com:9100']
  
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['app-docker355640.westeurope.cloudapp.azure.com:9093']

rule_files:
  - "rules.yml"
